# Generated by Django 2.2.12 on 2020-05-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='授权'),
        ),
        migrations.AlterField(
            model_name='comicpath',
            name='database_path',
            field=models.CharField(default='comic_book', max_length=20, verbose_name='此书库名'),
        ),
        migrations.AlterField(
            model_name='comicpath',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='book.ComicBook'),
        ),
        migrations.AlterField(
            model_name='comicpath',
            name='open_name',
            field=models.CharField(default='open', max_length=100, verbose_name='免费dir'),
        ),
        migrations.AlterField(
            model_name='comicpath',
            name='table_path',
            field=models.CharField(default='book_picturename', max_length=20, verbose_name='此书表名'),
        ),
        migrations.AlterField(
            model_name='comicpath',
            name='vip_name',
            field=models.CharField(default='vip', max_length=100, verbose_name='会员dir'),
        ),
    ]
