# Generated by Django 2.2.12 on 2020-05-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200521_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicpath',
            name='database_path',
        ),
        migrations.RemoveField(
            model_name='comicpath',
            name='table_path',
        ),
    ]
